### ISSUE TITLE
Gestures 

### ISSUE THREAD

**Issue by joshakinsola** [groupnoto/semicolon#10]
Important app features 

• Delete line of code by tapping 3 times 
• Show colour picker input 
• menu dialog to input basic shapes
ability to pause live rendering 

Can these be implemented?

**Comment by nicknikolov** [comment]
@joshakinsola I'm closing this issue since it's vague and undocumented. The first two fixtures are implemented. They need to be tested and if some UI/UX design changes spring out of user testing or anything, then please open new issues with EXACT DOCUMENTATION OF WHAT NEEDS TO BE DONE. I'm not shouting but please make my life easier. 
Also for 'menu dialog', again - please do the design, describe it for me, in a new issue of course.
cc @ma201ec @cuddeford
